# Basic experiment settings
experiment_name: "qwen_on_fld_step1"
model_name: "qwen2.5-7b-instruct"
dataset_name: "FLD"
max_workers: 5

# Path settings (using placeholders)
# {dataset_name} and {model_name} will be dynamically replaced by the program
run_tasks: ['rtg_process']       # Corresponds to run_settings2.sh workflow

# Specific parameters for rtg_label tasks (replacing SITUATIONS array in shell scripts)
rtg_label_settings:
  # You can specify specific situations to run here
  situations: ["All_Wrong", "2Over3_Wrong", "Half_Wrong", "All_Right"]
paths:
  # --- Common paths ---
  # Raw dataset path template
  raw_dataset_template: "data/{dataset_name}.json"

  # --- Vanilla Pipeline paths ---
  # Step1 (preprocessing) output "False UNKNOWN" samples path template
  step1_output_template: "results/False UNKNOWN_{dataset_name}_1_{model_name}.json"
  # Step2 (preprocessing) output "False UNKNOWN" samples path template (though we merge in memory, keep for debugging)
  step2_output_template: "results/False UNKNOWN_{dataset_name}_2_{model_name}.json"
  # Stage 1 Stimulation (step4) processed dataset
  step4_postprocess_template: "results/False UNKNOWN_{dataset_name}_Postprocess1_{model_name}.json"
  # Stage 2 Reflection (step5) final processed dataset
  step5_final_output_template: "results/False UNKNOWN_{dataset_name}_Postprocess2_{model_name}.json"

  # --- RtG Label Conformity paths ---
  # Save RtG Label test final evaluation results by situation
  rtg_label_eval_template: "results/evaluation_{dataset_name}_{model_name}_rtg_label_{situation}.json"

  # --- RtG Process Conformity paths ---
  # Step4 (process guidance) output
  rtg_process_step4_output_template: "results/False UNKNOWN_{dataset_name}_Postprocess_Reflection1_{model_name}.json"
  # Step5 (intermediate evaluation) output
  rtg_process_step5_output_template: "results/False UNKNOWN_{dataset_name}_Postprocess_Reflection2_{model_name}.json"
  # Step6 (final evaluation) output
  rtg_process_final_eval_template: "results/evaluation_{dataset_name}_{model_name}_rtg_process_final.json"